---
- name: ensure /etc/wireguard is created locally and all peers
  file:
    path: /etc/wireguard
    state: directory
    mode: 0700
  delegate_to: "{{ item }}"
  with_items: 
    - "{{ ansible_hostname }}"
    - "{{ wgpeers }}"

- name: ensure wg is installed
  apt:
    update_cache: yes
    state: present
    pkg:
      - wireguard
      - wireguard-tools
      - resolvconf

- name: allow ipv4 forwarding on host
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: setup wg0 interface
  blockinfile:
    path: /etc/wireguard/wg0.conf
    create: yes
    owner: root
    group: root
    mode: 0600
    marker: "# {mark} BLOCK interface"
    block: |
      [Interface]
      Address = {{ wgip }}
      DNS = 1.1.1.1
      ListenPort = 51820
      PrivateKey = {{ wgpriv }}
      PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
      PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
  no_log: true
  notify: restart_wg
  tags: interface

- name: Enable wg-quick@wg0 service
  service:
    name: wg-quick@wg0
    enabled: yes

- name: deploy pubkey to peers
  blockinfile:
    path: /etc/wireguard/wg0.conf
    create: yes
    marker: "# {mark} BLOCK {{ ansible_hostname }}"
    block: |
      [Peer]
      PublicKey={{ wgpub }}
      AllowedIPs={{ wgallow }}
      Endpoint={{ hostvars[inventory_hostname]['ansible_host'] }}:51820
  delegate_to: "{{ item }}"
  with_items: "{{ wgpeers }}"
  notify: restart_wg
  tags: peers
