---
- name: ensure /etc/wireguard is created locally and on all gateways
  file:
    path: /etc/wireguard
    state: directory
    mode: 0700
  delegate_to: "{{ item }}"
  with_items: 
    - "{{ ansible_hostname }}"
    - "{{ wggateways | default([]) }}"

- name: ensure /etc/wireguard is created on clients (workaround for undefined wgclients)
  file:
    path: /etc/wireguard
    state: directory
    mode: 0700
  when: wgclients is defined
  delegate_to: "{{ item }}"
  with_items:
    - "{{ wgclients.keys() | list }}"

- name: ensure wg and related packages are installed
  apt:
    update_cache: yes
    state: present
    pkg:
      - wireguard
      - wireguard-tools
      - resolvconf

- name: enable ipv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: setup wg0 interface
  blockinfile:
    path: /etc/wireguard/wg0.conf
    create: yes
    owner: root
    group: root
    mode: 0600
    marker: "# {mark} {{ ansible_hostname }} interface block"
    block: |
      [Interface]
      Address = {{ wgip }}
      DNS = 1.1.1.1
      ListenPort = 51820
      PrivateKey = {{ wgpriv }}
      PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE; iptables -t nat -A POSTROUTING -o wg -j MASQUERADE
      PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE; iptables -t nat -D POSTROUTING -o wg -j MASQUERADE
  no_log: true
  notify: restart_wg
  tags: interface

- name: Enable wg-quick@wg0 service
  service:
    name: wg-quick@wg0
    enabled: yes

- name: deploy pubkey and subnets to clients
  blockinfile:
    path: /etc/wireguard/wg0.conf
    create: yes
    marker: "# {mark} {{ ansible_hostname }} block"
    block: |
      [Peer]
      PublicKey={{ wgpub }}
      AllowedIPs={{ wgclients[item] }}, {{ wgip }}
      Endpoint={{ hostvars[inventory_hostname]['ansible_host'] }}:51820
  delegate_to: "{{ item }}"
  with_items: "{{ wgclients.keys() | list }}"
  when: wgclients is defined
  tags: clients

- name: deploy pubkey to gateways
  blockinfile:
    path: /etc/wireguard/wg0.conf
    create: yes
    marker: "# {mark} BLOCK {{ ansible_hostname }}"
    block: |
      [Peer]
      PublicKey={{ wgpub }}
      AllowedIPs={{ wgip }}
      Endpoint={{ hostvars[inventory_hostname]['ansible_host'] }}:51820
  delegate_to: "{{ item }}"
  with_items: "{{ wggateways }}"
  when: wggateways is defined
  tags: gateways
